### ISSUE TITLE
game rac

### ISSUE THREAD

**Issue by TinLite** [SatoriSimp/Fumo-Rescuer#1]
de nghi xoa game

**Comment by Baronah** [comment]
m ngu
t hay

**Comment by Seggsc0nd** [comment]
Ngay khi tôi vừa tải xong game, cuộc đời tôi đã được cứu rỗi. Tôi không còn chơi Liên Minh Huyền Thoại rank đơn đôi. Tôi đã từ bỏ Genshin Impact. Tôi đã không còn ám ảnh với Siegwinne Genshin Impact. Cảm ơn nhà phát hành đã góp phần giúp cuộc đời tôi trở nên tốt đẹp hơn. Đề nghị xóa game.

**Comment by Baronah** [comment]
> Ngay khi tôi vừa tải xong game, cuộc đời tôi đã được cứu rỗi. Tôi không còn chơi Liên Minh Huyền Thoại rank đơn đôi. Tôi đã từ bỏ Genshin Impact. Tôi đã không còn ám ảnh với Siegwinne Genshin Impact. Cảm ơn nhà phát hành đã góp phần giúp cuộc đời tôi trở nên tốt đẹp hơn. Đề nghị xóa game.

@Seggsc0nd ogmbd
